library(wordcloud)
library(RColorBrewer)
setwd("~/Capstone/Meta/MetaData")
data <- read.csv("noun.csv", sep = '\t', header = FALSE)
as.numeric(data[,2])
pal1 <- brewer.pal(8, "Dark2")
wordcloud(words=data[,1], random.order=FALSE, colors=pal1, rot.per=.15, freq = data[,2], min.freq=5)
verb <- read.csv("verb.csv", sep = '\t', header=FALSE)
pal2 <- brewer.pal(8, "Set2")
wordcloud(words = verb[-477,1], random.order=FALSE, scale = c(8,0.2), colors = pal2, rot.per = 0.15, freq = as.numeric(verb[-477,2]), min.freq=3)
# Sample Code
word <- c("SixSpokeMedia", "Advertising", "Search","Campaign", "e-commerce", "Strategy")
freq <- c(12,10,8,5,5,5,4,3,2,2,1)
wordcloud(words = word, random.order=FALSE, scale = c(3, 0.2), colors = pal3, rot.per = 0.15, freq = freq, min.freq=1)
